### ISSUE TITLE
Fail to compile/make

### ISSUE THREAD

**Issue by Isemenuk27** [openwrt/rtl8126#3]
Using make inside src:
`user@debian:~/Downloads/r8126-10.014.01/src$ make

CC:  cc
CCVERSION:  12
KERNEL_GCC_VERSION: 
KVER:  6.1.0-28-amd64
KMAJ:  6
KMIN:  1
KREV:  0
BASEDIR:  /lib/modules/6.1.0-28-amd64
DRIVERDIR:  /lib/modules/6.1.0-28-amd64/kernel/drivers/net/ethernet/realtek
PWD:  /home/user/Downloads/r8126-10.014.01/src
RTKDIR:  kernel/drivers/net/ethernet/realtek

make -C /lib/modules/6.1.0-28-amd64/build M=/home/user/Downloads/r8126-10.014.01/src clean
make[1]: Entering directory '/usr/lib/modules/6.1.0-28-amd64/build'
make[1]: *** No rule to make target 'clean'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/6.1.0-28-amd64/build'
make: *** [Makefile:201: clean] Error 2
`
Using autorun.sh

`user@debian:~/Downloads/r8126-10.014.01$ sudo ./autorun.sh
[sudo] password for user: 

Check old driver and unload it.
Build the module and install
make[2]: *** No rule to make target 'clean'.  Stop.
make[1]: *** [Makefile:201: clean] Error 2
make: *** [Makefile:48: clean] Error 2
`

Sorry, but I'm couldn't find any solutions and I'm weak in makefiles.

**Comment by Isemenuk27** [comment]
Fixed, by deleting switching on Fedora...

**Comment by Noltari** [comment]
@Isemenuk27 this repo is for OpenWrt compilation purposes only.
Any issues not specifically related to OpenWrt should be reported to Realtek.
